spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workout_tracker  # Match the name you gave in docker-compose
    username: admin  # Match the username from docker-compose
    password: topsecret  # Match the password from docker-compose
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: none  # Adjust based on your needs (create, update, validate, etc.)
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/workout_tracker
#    username: admin
#    password: topsecret

server:
  port: 8080  # Spring Boot will run on port 8080 by default

